import type { UserProfile } from "./types"

export const DUMMY_PROFILES: UserProfile[] = [
  {
    id: "user_1",
    name: "John Doe",
    email: "john.doe@example.com",
    age: 35,
    gender: "Male",
    height: 175,
    weight: 80,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000, // 90 days ago
    lastActiveAt: Date.now() - 1 * 24 * 60 * 60 * 1000, // 1 day ago
    primaryInjuryArea: "Shoulder",
    injuryDescription: "Rotator cuff injury recovery",
    injuryDate: Date.now() - 180 * 24 * 60 * 60 * 1000,
    painThreshold: 6,
    previousPTExperience: true,
    currentPainLevel: 3,
    plan: {
      name: "Shoulder Rehabilitation Program",
      injuryArea: "Shoulder",
      exercises: [
        { exercise: "Shoulder Raise", sets: 3, reps: 12, tempo: "Slow", notes: "Control the movement" },
        { exercise: "Shoulder Press", sets: 2, reps: 10, tempo: "Normal", notes: "Keep trunk upright" },
      ],
      daysPerWeek: 3,
      preferredDays: ["Mon", "Wed", "Fri"],
      reminderTime: "07:00",
      painThreshold: 6,
    },
    totalSessions: 25,
    currentStreak: 5,
    longestStreak: 12,
    totalRepsAllTime: 1250,
    improvementTrend: "improving",
    favoriteExercise: "Squat",
    mostChallengingExercise: "Lunge",
    averageSessionDuration: 1800,
    complianceRate: 85,
    voiceCoachEnabled: true,
    demoWatched: { Squat: true, Lunge: true, "Calf Raise": true },
    notificationsEnabled: true,
    preferredWorkoutTime: "Morning",
  },
  {
    id: "user_2",
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    age: 42,
    gender: "Female",
    height: 162,
    weight: 65,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Shoulder",
    injuryDescription: "Rotator cuff strain from overhead work",
    injuryDate: Date.now() - 120 * 24 * 60 * 60 * 1000,
    painThreshold: 5,
    previousPTExperience: false,
    currentPainLevel: 4,
    plan: {
      name: "Shoulder Strengthening Program",
      injuryArea: "Shoulder",
      exercises: [
        { exercise: "Shoulder Raise", sets: 3, reps: 12, tempo: "Slow", notes: "Control the movement" },
        { exercise: "Shoulder Press", sets: 2, reps: 10, tempo: "Normal", notes: "Keep trunk upright" },
      ],
      daysPerWeek: 4,
      preferredDays: ["Mon", "Tue", "Thu", "Fri"],
      reminderTime: "18:00",
      painThreshold: 5,
    },
    totalSessions: 18,
    currentStreak: 3,
    longestStreak: 8,
    totalRepsAllTime: 850,
    improvementTrend: "improving",
    favoriteExercise: "Shoulder Raise",
    mostChallengingExercise: "Shoulder Press",
    averageSessionDuration: 1200,
    complianceRate: 75,
    voiceCoachEnabled: false,
    demoWatched: { "Shoulder Raise": true, "Shoulder Press": true },
    notificationsEnabled: true,
    preferredWorkoutTime: "Evening",
  },
  {
    id: "user_3",
    name: "Michael Rodriguez",
    email: "michael.r@example.com",
    age: 28,
    gender: "Male",
    height: 180,
    weight: 85,
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 0.5 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Back",
    injuryDescription: "Lower back pain from desk work",
    injuryDate: Date.now() - 90 * 24 * 60 * 60 * 1000,
    painThreshold: 7,
    previousPTExperience: true,
    currentPainLevel: 2,
    plan: {
      name: "Back Pain Relief Plan",
      injuryArea: "Back",
      exercises: [
        { exercise: "Hip Hinge", sets: 3, reps: 12, tempo: "Slow", notes: "Keep knees straight" },
        { exercise: "Squat", sets: 3, reps: 10, tempo: "Normal", notes: "Maintain neutral spine" },
      ],
      daysPerWeek: 5,
      preferredDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      reminderTime: "12:00",
      painThreshold: 7,
    },
    totalSessions: 32,
    currentStreak: 12,
    longestStreak: 15,
    totalRepsAllTime: 1800,
    improvementTrend: "improving",
    favoriteExercise: "Hip Hinge",
    mostChallengingExercise: "Squat",
    averageSessionDuration: 1500,
    complianceRate: 92,
    voiceCoachEnabled: true,
    demoWatched: { "Hip Hinge": true, Squat: true },
    notificationsEnabled: true,
    preferredWorkoutTime: "Afternoon",
  },
  {
    id: "user_4",
    name: "Emily Johnson",
    email: "emily.j@example.com",
    age: 55,
    gender: "Female",
    height: 168,
    weight: 70,
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Hip",
    injuryDescription: "Hip replacement recovery",
    injuryDate: Date.now() - 200 * 24 * 60 * 60 * 1000,
    painThreshold: 4,
    previousPTExperience: true,
    currentPainLevel: 3,
    plan: {
      name: "Hip Recovery Program",
      injuryArea: "Hip",
      exercises: [
        { exercise: "Squat", sets: 2, reps: 8, tempo: "Slow", notes: "Shallow depth initially" },
        { exercise: "Hip Hinge", sets: 2, reps: 10, tempo: "Slow", notes: "Focus on hip mobility" },
        { exercise: "Lunge", sets: 2, reps: 8, tempo: "Slow", notes: "Use support if needed" },
      ],
      daysPerWeek: 3,
      preferredDays: ["Mon", "Wed", "Fri"],
      reminderTime: "09:00",
      painThreshold: 4,
    },
    totalSessions: 15,
    currentStreak: 0,
    longestStreak: 6,
    totalRepsAllTime: 600,
    improvementTrend: "stable",
    favoriteExercise: "Hip Hinge",
    mostChallengingExercise: "Lunge",
    averageSessionDuration: 2000,
    complianceRate: 65,
    voiceCoachEnabled: true,
    demoWatched: { Squat: true, "Hip Hinge": true, Lunge: false },
    notificationsEnabled: true,
    preferredWorkoutTime: "Morning",
  },
  {
    id: "user_5",
    name: "David Kim",
    email: "david.kim@example.com",
    age: 31,
    gender: "Male",
    height: 178,
    weight: 82,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 0.1 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Ankle",
    injuryDescription: "Ankle sprain from basketball",
    injuryDate: Date.now() - 45 * 24 * 60 * 60 * 1000,
    painThreshold: 6,
    previousPTExperience: false,
    currentPainLevel: 2,
    plan: {
      name: "Ankle Rehabilitation",
      injuryArea: "Ankle",
      exercises: [
        { exercise: "Calf Raise", sets: 3, reps: 15, tempo: "Normal", notes: "Full range of motion" },
        { exercise: "Squat", sets: 3, reps: 12, tempo: "Normal", notes: "Watch ankle alignment" },
      ],
      daysPerWeek: 4,
      preferredDays: ["Mon", "Wed", "Fri", "Sat"],
      reminderTime: "17:00",
      painThreshold: 6,
    },
    totalSessions: 12,
    currentStreak: 7,
    longestStreak: 7,
    totalRepsAllTime: 720,
    improvementTrend: "improving",
    favoriteExercise: "Calf Raise",
    mostChallengingExercise: "Squat",
    averageSessionDuration: 1400,
    complianceRate: 88,
    voiceCoachEnabled: false,
    demoWatched: { "Calf Raise": true, Squat: true },
    notificationsEnabled: true,
    preferredWorkoutTime: "Evening",
  },
  {
    id: "user_6",
    name: "Jessica Martinez",
    email: "jessica.m@example.com",
    age: 38,
    gender: "Female",
    height: 165,
    weight: 68,
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Knee",
    injuryDescription: "Patellofemoral pain syndrome",
    injuryDate: Date.now() - 60 * 24 * 60 * 60 * 1000,
    painThreshold: 5,
    previousPTExperience: true,
    currentPainLevel: 3,
    plan: {
      name: "Knee Strengthening",
      injuryArea: "Knee",
      exercises: [
        { exercise: "Squat", sets: 3, reps: 10, tempo: "Slow", notes: "Control descent" },
        { exercise: "Lunge", sets: 2, reps: 10, tempo: "Slow", notes: "Equal weight distribution" },
      ],
      daysPerWeek: 3,
      preferredDays: ["Tue", "Thu", "Sat"],
      reminderTime: "08:00",
      painThreshold: 5,
    },
    totalSessions: 8,
    currentStreak: 2,
    longestStreak: 4,
    totalRepsAllTime: 320,
    improvementTrend: "stable",
    favoriteExercise: "Squat",
    mostChallengingExercise: "Lunge",
    averageSessionDuration: 1600,
    complianceRate: 70,
    voiceCoachEnabled: true,
    demoWatched: { Squat: true, Lunge: false },
    notificationsEnabled: true,
    preferredWorkoutTime: "Morning",
  },
  {
    id: "user_7",
    name: "Robert Taylor",
    email: "robert.t@example.com",
    age: 48,
    gender: "Male",
    height: 183,
    weight: 90,
    createdAt: Date.now() - 75 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Shoulder",
    injuryDescription: "Frozen shoulder recovery",
    injuryDate: Date.now() - 150 * 24 * 60 * 60 * 1000,
    painThreshold: 5,
    previousPTExperience: false,
    currentPainLevel: 4,
    plan: {
      name: "Shoulder Mobility Program",
      injuryArea: "Shoulder",
      exercises: [
        { exercise: "Shoulder Raise", sets: 3, reps: 10, tempo: "Slow", notes: "Gentle range of motion" },
        { exercise: "Shoulder Press", sets: 2, reps: 8, tempo: "Slow", notes: "Light weight only" },
      ],
      daysPerWeek: 4,
      preferredDays: ["Mon", "Tue", "Thu", "Fri"],
      reminderTime: "19:00",
      painThreshold: 5,
    },
    totalSessions: 22,
    currentStreak: 0,
    longestStreak: 9,
    totalRepsAllTime: 950,
    improvementTrend: "declining",
    favoriteExercise: "Shoulder Raise",
    mostChallengingExercise: "Shoulder Press",
    averageSessionDuration: 1800,
    complianceRate: 60,
    voiceCoachEnabled: false,
    demoWatched: { "Shoulder Raise": true, "Shoulder Press": true },
    notificationsEnabled: false,
    preferredWorkoutTime: "Evening",
  },
  {
    id: "user_8",
    name: "Amanda Wilson",
    email: "amanda.w@example.com",
    age: 29,
    gender: "Female",
    height: 170,
    weight: 72,
    createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastActiveAt: Date.now() - 0.2 * 24 * 60 * 60 * 1000,
    primaryInjuryArea: "Back",
    injuryDescription: "Lower back strain from lifting",
    injuryDate: Date.now() - 35 * 24 * 60 * 60 * 1000,
    painThreshold: 7,
    previousPTExperience: true,
    currentPainLevel: 2,
    plan: {
      name: "Back Strengthening",
      injuryArea: "Back",
      exercises: [
        { exercise: "Hip Hinge", sets: 3, reps: 12, tempo: "Normal", notes: "Maintain core engagement" },
        { exercise: "Squat", sets: 3, reps: 10, tempo: "Normal", notes: "Keep back straight" },
      ],
      daysPerWeek: 4,
      preferredDays: ["Mon", "Wed", "Fri", "Sun"],
      reminderTime: "06:30",
      painThreshold: 7,
    },
    totalSessions: 14,
    currentStreak: 6,
    longestStreak: 6,
    totalRepsAllTime: 840,
    improvementTrend: "improving",
    favoriteExercise: "Hip Hinge",
    mostChallengingExercise: "Squat",
    averageSessionDuration: 1650,
    complianceRate: 90,
    voiceCoachEnabled: true,
    demoWatched: { "Hip Hinge": true, Squat: true },
    notificationsEnabled: true,
    preferredWorkoutTime: "Morning",
  },
]

